### ISSUE TITLE
Crash when starting game (Uplink 1.2.1)

### ISSUE THREAD

**Issue by BBoldt** [ijo42/Uplink#6]
One of the users of my 1.7.10 modpack that includes Uplink got this crash when trying to start his game. I thought it might have something to do with his java version but i'm not so sure.

https://pastebin.com/aGjRmhGp

https://github.com/elytra/Unabridged/issues/632

**Comment by ijo42** [comment]
Hmm, never met one. But this is clearly a mistake on the part of DiscordIPC Lib, but I don't see any similar issues in its repo, and the library is popular, funny. I can also assume that the problem is observed only on Windows 7.
i'll try to play around with the library modifications for better effect, but in the meantime, you can use version 1.1.5, which is based on the native library
Good luck

**Comment by Fuhrmaaj** [comment]
Hey, someone called "spinel" dropped into our Discord with a file called Uplink-MC1.7.10-1.2.2-RC1.jar

I am the Windows 7 user that crashed with Uplink, and as far as I can tell, this version solved the issue. I'll let you know if anything changes!
